name: Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    name: Build ipa and deb
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Update submodules
        run: git submodule update --init --recursive
      - name: Build using cmake
        run: make all
