name: CI
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build ipa and deb
    runs-on: macos-10.15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Update submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: brew install dpkg ldid
      - name: Build using cmake
        run: make all
      - uses: actions/upload-artifact@v2
        with:
          name: ppsspp-binaries
          path: |
            *.ipa
            *.deb
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload PPSSPP ipa
        id: upload-ppsspp-ipa
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./PPSSPP_${{ steps.get_version.outputs.VERSION }}.ipa
          asset_name: PPSSPP_${{ steps.get_version.outputs.VERSION }}.ipa
          asset_content_type: application/octet-stream
      - name: Upload PPSSPP deb
        id: upload-ppsspp-deb
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./org.ppsspp.ppsspp-dev-latest_${{ steps.get_version.outputs.VERSION }}_iphoneos-arm.deb
          asset_name: org.ppsspp.ppsspp-dev-latest_${{ steps.get_version.outputs.VERSION }}_iphoneos-arm.deb
          asset_content_type: application/x-debian-package
